name: On Pull Request Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened] # Target specific PR events

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04 # We can also use "ubuntu-latest" for latest LTS version
    steps:
      - name: Checkout
        uses: actions/checkout@v3 # Checkout the code at the current commit
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint

  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm run test

  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build

  notify:
    name: Notify
    runs-on: ubuntu-20.04
    needs: [lint, test, build]
    steps:
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          channel-id: ${{ secrets.CHANNEL_ID }} # Secrets are defined in the settings of your repository
          slack-message: "New PR event in ${{ github.repository }}\nLink: ${{ github.event.pull_request.html_url }}" # See all available context variables: https://docs.github.com/en/actions/learn-github-actions/contexts
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
